// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeInformable creates a new instance of MockNodeInformable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeInformable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeInformable {
	mock := &MockNodeInformable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeInformable is an autogenerated mock type for the NodeInformable type
type MockNodeInformable struct {
	mock.Mock
}

type MockNodeInformable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeInformable) EXPECT() *MockNodeInformable_Expecter {
	return &MockNodeInformable_Expecter{mock: &_m.Mock}
}

// AddTag provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) AddTag(s string) {
	_mock.Called(s)
	return
}

// MockNodeInformable_AddTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTag'
type MockNodeInformable_AddTag_Call struct {
	*mock.Call
}

// AddTag is a helper method to define mock.On call
//   - s string
func (_e *MockNodeInformable_Expecter) AddTag(s interface{}) *MockNodeInformable_AddTag_Call {
	return &MockNodeInformable_AddTag_Call{Call: _e.mock.On("AddTag", s)}
}

func (_c *MockNodeInformable_AddTag_Call) Run(run func(s string)) *MockNodeInformable_AddTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeInformable_AddTag_Call) Return() *MockNodeInformable_AddTag_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeInformable_AddTag_Call) RunAndReturn(run func(s string)) *MockNodeInformable_AddTag_Call {
	_c.Run(run)
	return _c
}

// DeleteTag provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) DeleteTag(s string) {
	_mock.Called(s)
	return
}

// MockNodeInformable_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockNodeInformable_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - s string
func (_e *MockNodeInformable_Expecter) DeleteTag(s interface{}) *MockNodeInformable_DeleteTag_Call {
	return &MockNodeInformable_DeleteTag_Call{Call: _e.mock.On("DeleteTag", s)}
}

func (_c *MockNodeInformable_DeleteTag_Call) Run(run func(s string)) *MockNodeInformable_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeInformable_DeleteTag_Call) Return() *MockNodeInformable_DeleteTag_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeInformable_DeleteTag_Call) RunAndReturn(run func(s string)) *MockNodeInformable_DeleteTag_Call {
	_c.Run(run)
	return _c
}

// GetAbsPath provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) GetAbsPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAbsPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeInformable_GetAbsPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAbsPath'
type MockNodeInformable_GetAbsPath_Call struct {
	*mock.Call
}

// GetAbsPath is a helper method to define mock.On call
func (_e *MockNodeInformable_Expecter) GetAbsPath() *MockNodeInformable_GetAbsPath_Call {
	return &MockNodeInformable_GetAbsPath_Call{Call: _e.mock.On("GetAbsPath")}
}

func (_c *MockNodeInformable_GetAbsPath_Call) Run(run func()) *MockNodeInformable_GetAbsPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeInformable_GetAbsPath_Call) Return(s string) *MockNodeInformable_GetAbsPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeInformable_GetAbsPath_Call) RunAndReturn(run func() string) *MockNodeInformable_GetAbsPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) GetId() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNodeInformable_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MockNodeInformable_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MockNodeInformable_Expecter) GetId() *MockNodeInformable_GetId_Call {
	return &MockNodeInformable_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MockNodeInformable_GetId_Call) Run(run func()) *MockNodeInformable_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeInformable_GetId_Call) Return(s string) *MockNodeInformable_GetId_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNodeInformable_GetId_Call) RunAndReturn(run func() string) *MockNodeInformable_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetTags provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) GetTags() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTags")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNodeInformable_GetTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTags'
type MockNodeInformable_GetTags_Call struct {
	*mock.Call
}

// GetTags is a helper method to define mock.On call
func (_e *MockNodeInformable_Expecter) GetTags() *MockNodeInformable_GetTags_Call {
	return &MockNodeInformable_GetTags_Call{Call: _e.mock.On("GetTags")}
}

func (_c *MockNodeInformable_GetTags_Call) Run(run func()) *MockNodeInformable_GetTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeInformable_GetTags_Call) Return(strings []string) *MockNodeInformable_GetTags_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNodeInformable_GetTags_Call) RunAndReturn(run func() []string) *MockNodeInformable_GetTags_Call {
	_c.Call.Return(run)
	return _c
}

// SetId provides a mock function for the type MockNodeInformable
func (_mock *MockNodeInformable) SetId(s string) {
	_mock.Called(s)
	return
}

// MockNodeInformable_SetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetId'
type MockNodeInformable_SetId_Call struct {
	*mock.Call
}

// SetId is a helper method to define mock.On call
//   - s string
func (_e *MockNodeInformable_Expecter) SetId(s interface{}) *MockNodeInformable_SetId_Call {
	return &MockNodeInformable_SetId_Call{Call: _e.mock.On("SetId", s)}
}

func (_c *MockNodeInformable_SetId_Call) Run(run func(s string)) *MockNodeInformable_SetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeInformable_SetId_Call) Return() *MockNodeInformable_SetId_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeInformable_SetId_Call) RunAndReturn(run func(s string)) *MockNodeInformable_SetId_Call {
	_c.Run(run)
	return _c
}
