// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filesys

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScanner creates a new instance of MockScanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScanner {
	mock := &MockScanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScanner is an autogenerated mock type for the Scanner type
type MockScanner struct {
	mock.Mock
}

type MockScanner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScanner) EXPECT() *MockScanner_Expecter {
	return &MockScanner_Expecter{mock: &_m.Mock}
}

// Scan provides a mock function for the type MockScanner
func (_mock *MockScanner) Scan(path string) (*ds.TreeNode, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ds.TreeNode, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ds.TreeNode); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScanner_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockScanner_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - path string
func (_e *MockScanner_Expecter) Scan(path interface{}) *MockScanner_Scan_Call {
	return &MockScanner_Scan_Call{Call: _e.mock.On("Scan", path)}
}

func (_c *MockScanner_Scan_Call) Run(run func(path string)) *MockScanner_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScanner_Scan_Call) Return(treeNode *ds.TreeNode, err error) *MockScanner_Scan_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockScanner_Scan_Call) RunAndReturn(run func(path string) (*ds.TreeNode, error)) *MockScanner_Scan_Call {
	_c.Call.Return(run)
	return _c
}
