all: false
template: testify
packages:
  github.com/heroku/self/MetaManager/internal/services:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      GDriveServiceInterface:
  github.com/heroku/self/MetaManager/internal/filesys:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      Scanner:
      ScannableNode:
      Tracker:
  github.com/heroku/self/MetaManager/internal/repository/filesys:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ContextRepository:
  github.com/heroku/self/MetaManager/internal/storage:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      TreeReader:
      TreeWriter:
      TreeRW:
      RWFactory:
  github.com/heroku/self/MetaManager/internal/file:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      NodeInformable:
      SerializableNode:
      TagsPrinter:
      NodePrinter:
      IdPrinter:
  github.com/heroku/self/MetaManager/internal/printer:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ListPrintable:
      PrintingContext:
  github.com/heroku/self/MetaManager/internal/ds:
    config:
      dir: "mocks"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      TreeIterable:
      NodeIterable:
      InfoSerializer:
      TreeNodeInformable:
