all: false
template: testify
packages:
  github.com/heroku/self/MetaManager/internal/services:
    config:
      dir: "internal/mocks/services"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      GDriveServiceInterface:
  github.com/heroku/self/MetaManager/internal/filesys:
    config:
      dir: "internal/mocks/filesys"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      Scanner:
      ScannableNode:
      Tracker:
  github.com/heroku/self/MetaManager/internal/repository/context:
    config:
      dir: "internal/mocks/repository/context"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ContextRepository:
  github.com/heroku/self/MetaManager/internal/repository/tree:
    config:
      dir: "internal/mocks/repository/tree"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      TreeReader:
      TreeWriter:
      TreeRW:
      RWFactory:
  github.com/heroku/self/MetaManager/internal/file:
    config:
      dir: "internal/mocks/file"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      NodeInformable:
      SerializableNode:
      TagsPrinter:
      NodePrinter:
      IdPrinter:
  github.com/heroku/self/MetaManager/internal/printer:
    config:
      dir: "internal/mocks/printer"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ListPrintable:
      PrintingContext:
  github.com/heroku/self/MetaManager/internal/ds:
    config:
      dir: "internal/mocks/ds"
      filename: "mock_{{.InterfaceName}}.go"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      TreeIterable:
      NodeIterable:
      InfoUnmarshaler:
      TreeNodeInformable:
