// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package printer

import (
	"github.com/jedib0t/go-pretty/v6/list"
	mock "github.com/stretchr/testify/mock"
)

// NewMockListPrintable creates a new instance of MockListPrintable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListPrintable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListPrintable {
	mock := &MockListPrintable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockListPrintable is an autogenerated mock type for the ListPrintable type
type MockListPrintable struct {
	mock.Mock
}

type MockListPrintable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListPrintable) EXPECT() *MockListPrintable_Expecter {
	return &MockListPrintable_Expecter{mock: &_m.Mock}
}

// Print provides a mock function for the type MockListPrintable
func (_mock *MockListPrintable) Print(writer list.Writer) {
	_mock.Called(writer)
	return
}

// MockListPrintable_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type MockListPrintable_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - writer list.Writer
func (_e *MockListPrintable_Expecter) Print(writer interface{}) *MockListPrintable_Print_Call {
	return &MockListPrintable_Print_Call{Call: _e.mock.On("Print", writer)}
}

func (_c *MockListPrintable_Print_Call) Run(run func(writer list.Writer)) *MockListPrintable_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 list.Writer
		if args[0] != nil {
			arg0 = args[0].(list.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockListPrintable_Print_Call) Return() *MockListPrintable_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockListPrintable_Print_Call) RunAndReturn(run func(writer list.Writer)) *MockListPrintable_Print_Call {
	_c.Run(run)
	return _c
}
