// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeRW creates a new instance of MockTreeRW. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeRW(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeRW {
	mock := &MockTreeRW{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeRW is an autogenerated mock type for the TreeRW type
type MockTreeRW struct {
	mock.Mock
}

type MockTreeRW_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeRW) EXPECT() *MockTreeRW_Expecter {
	return &MockTreeRW_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockTreeRW
func (_mock *MockTreeRW) Read() (*ds.TreeNode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ds.TreeNode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ds.TreeNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeRW_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockTreeRW_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockTreeRW_Expecter) Read() *MockTreeRW_Read_Call {
	return &MockTreeRW_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockTreeRW_Read_Call) Run(run func()) *MockTreeRW_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTreeRW_Read_Call) Return(treeNode *ds.TreeNode, err error) *MockTreeRW_Read_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockTreeRW_Read_Call) RunAndReturn(run func() (*ds.TreeNode, error)) *MockTreeRW_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type MockTreeRW
func (_mock *MockTreeRW) Write(treeNode *ds.TreeNode) error {
	ret := _mock.Called(treeNode)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*ds.TreeNode) error); ok {
		r0 = returnFunc(treeNode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTreeRW_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockTreeRW_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - treeNode *ds.TreeNode
func (_e *MockTreeRW_Expecter) Write(treeNode interface{}) *MockTreeRW_Write_Call {
	return &MockTreeRW_Write_Call{Call: _e.mock.On("Write", treeNode)}
}

func (_c *MockTreeRW_Write_Call) Run(run func(treeNode *ds.TreeNode)) *MockTreeRW_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ds.TreeNode
		if args[0] != nil {
			arg0 = args[0].(*ds.TreeNode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeRW_Write_Call) Return(err error) *MockTreeRW_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTreeRW_Write_Call) RunAndReturn(run func(treeNode *ds.TreeNode) error) *MockTreeRW_Write_Call {
	_c.Call.Return(run)
	return _c
}
