// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeWriter creates a new instance of MockTreeWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeWriter {
	mock := &MockTreeWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeWriter is an autogenerated mock type for the TreeWriter type
type MockTreeWriter struct {
	mock.Mock
}

type MockTreeWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeWriter) EXPECT() *MockTreeWriter_Expecter {
	return &MockTreeWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockTreeWriter
func (_mock *MockTreeWriter) Write(treeNode *ds.TreeNode) error {
	ret := _mock.Called(treeNode)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*ds.TreeNode) error); ok {
		r0 = returnFunc(treeNode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTreeWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockTreeWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - treeNode *ds.TreeNode
func (_e *MockTreeWriter_Expecter) Write(treeNode interface{}) *MockTreeWriter_Write_Call {
	return &MockTreeWriter_Write_Call{Call: _e.mock.On("Write", treeNode)}
}

func (_c *MockTreeWriter_Write_Call) Run(run func(treeNode *ds.TreeNode)) *MockTreeWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *ds.TreeNode
		if args[0] != nil {
			arg0 = args[0].(*ds.TreeNode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTreeWriter_Write_Call) Return(err error) *MockTreeWriter_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTreeWriter_Write_Call) RunAndReturn(run func(treeNode *ds.TreeNode) error) *MockTreeWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
