// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeReader creates a new instance of MockTreeReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeReader {
	mock := &MockTreeReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeReader is an autogenerated mock type for the TreeReader type
type MockTreeReader struct {
	mock.Mock
}

type MockTreeReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeReader) EXPECT() *MockTreeReader_Expecter {
	return &MockTreeReader_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockTreeReader
func (_mock *MockTreeReader) Read() (*ds.TreeNode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ds.TreeNode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ds.TreeNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeReader_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockTreeReader_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
func (_e *MockTreeReader_Expecter) Read() *MockTreeReader_Read_Call {
	return &MockTreeReader_Read_Call{Call: _e.mock.On("Read")}
}

func (_c *MockTreeReader_Read_Call) Run(run func()) *MockTreeReader_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTreeReader_Read_Call) Return(treeNode *ds.TreeNode, err error) *MockTreeReader_Read_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockTreeReader_Read_Call) RunAndReturn(run func() (*ds.TreeNode, error)) *MockTreeReader_Read_Call {
	_c.Call.Return(run)
	return _c
}
