// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/heroku/self/MetaManager/internal/services"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGDriveServiceInterface creates a new instance of MockGDriveServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGDriveServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGDriveServiceInterface {
	mock := &MockGDriveServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGDriveServiceInterface is an autogenerated mock type for the GDriveServiceInterface type
type MockGDriveServiceInterface struct {
	mock.Mock
}

type MockGDriveServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGDriveServiceInterface) EXPECT() *MockGDriveServiceInterface_Expecter {
	return &MockGDriveServiceInterface_Expecter{mock: &_m.Mock}
}

// ListAtPath provides a mock function for the type MockGDriveServiceInterface
func (_mock *MockGDriveServiceInterface) ListAtPath(ctx context.Context, path string) ([]services.RootEntry, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ListAtPath")
	}

	var r0 []services.RootEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]services.RootEntry, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []services.RootEntry); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.RootEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGDriveServiceInterface_ListAtPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAtPath'
type MockGDriveServiceInterface_ListAtPath_Call struct {
	*mock.Call
}

// ListAtPath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGDriveServiceInterface_Expecter) ListAtPath(ctx interface{}, path interface{}) *MockGDriveServiceInterface_ListAtPath_Call {
	return &MockGDriveServiceInterface_ListAtPath_Call{Call: _e.mock.On("ListAtPath", ctx, path)}
}

func (_c *MockGDriveServiceInterface_ListAtPath_Call) Run(run func(ctx context.Context, path string)) *MockGDriveServiceInterface_ListAtPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGDriveServiceInterface_ListAtPath_Call) Return(rootEntrys []services.RootEntry, err error) *MockGDriveServiceInterface_ListAtPath_Call {
	_c.Call.Return(rootEntrys, err)
	return _c
}

func (_c *MockGDriveServiceInterface_ListAtPath_Call) RunAndReturn(run func(ctx context.Context, path string) ([]services.RootEntry, error)) *MockGDriveServiceInterface_ListAtPath_Call {
	_c.Call.Return(run)
	return _c
}

// ListFolder provides a mock function for the type MockGDriveServiceInterface
func (_mock *MockGDriveServiceInterface) ListFolder(ctx context.Context, folderID string) ([]services.RootEntry, error) {
	ret := _mock.Called(ctx, folderID)

	if len(ret) == 0 {
		panic("no return value specified for ListFolder")
	}

	var r0 []services.RootEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]services.RootEntry, error)); ok {
		return returnFunc(ctx, folderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []services.RootEntry); ok {
		r0 = returnFunc(ctx, folderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.RootEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, folderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGDriveServiceInterface_ListFolder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFolder'
type MockGDriveServiceInterface_ListFolder_Call struct {
	*mock.Call
}

// ListFolder is a helper method to define mock.On call
//   - ctx context.Context
//   - folderID string
func (_e *MockGDriveServiceInterface_Expecter) ListFolder(ctx interface{}, folderID interface{}) *MockGDriveServiceInterface_ListFolder_Call {
	return &MockGDriveServiceInterface_ListFolder_Call{Call: _e.mock.On("ListFolder", ctx, folderID)}
}

func (_c *MockGDriveServiceInterface_ListFolder_Call) Run(run func(ctx context.Context, folderID string)) *MockGDriveServiceInterface_ListFolder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGDriveServiceInterface_ListFolder_Call) Return(rootEntrys []services.RootEntry, err error) *MockGDriveServiceInterface_ListFolder_Call {
	_c.Call.Return(rootEntrys, err)
	return _c
}

func (_c *MockGDriveServiceInterface_ListFolder_Call) RunAndReturn(run func(ctx context.Context, folderID string) ([]services.RootEntry, error)) *MockGDriveServiceInterface_ListFolder_Call {
	_c.Call.Return(run)
	return _c
}

// ListRoot provides a mock function for the type MockGDriveServiceInterface
func (_mock *MockGDriveServiceInterface) ListRoot(ctx context.Context) ([]services.RootEntry, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListRoot")
	}

	var r0 []services.RootEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]services.RootEntry, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []services.RootEntry); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]services.RootEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGDriveServiceInterface_ListRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRoot'
type MockGDriveServiceInterface_ListRoot_Call struct {
	*mock.Call
}

// ListRoot is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGDriveServiceInterface_Expecter) ListRoot(ctx interface{}) *MockGDriveServiceInterface_ListRoot_Call {
	return &MockGDriveServiceInterface_ListRoot_Call{Call: _e.mock.On("ListRoot", ctx)}
}

func (_c *MockGDriveServiceInterface_ListRoot_Call) Run(run func(ctx context.Context)) *MockGDriveServiceInterface_ListRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGDriveServiceInterface_ListRoot_Call) Return(rootEntrys []services.RootEntry, err error) *MockGDriveServiceInterface_ListRoot_Call {
	_c.Call.Return(rootEntrys, err)
	return _c
}

func (_c *MockGDriveServiceInterface_ListRoot_Call) RunAndReturn(run func(ctx context.Context) ([]services.RootEntry, error)) *MockGDriveServiceInterface_ListRoot_Call {
	_c.Call.Return(run)
	return _c
}

// ResolvePath provides a mock function for the type MockGDriveServiceInterface
func (_mock *MockGDriveServiceInterface) ResolvePath(ctx context.Context, path string) (string, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ResolvePath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGDriveServiceInterface_ResolvePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolvePath'
type MockGDriveServiceInterface_ResolvePath_Call struct {
	*mock.Call
}

// ResolvePath is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockGDriveServiceInterface_Expecter) ResolvePath(ctx interface{}, path interface{}) *MockGDriveServiceInterface_ResolvePath_Call {
	return &MockGDriveServiceInterface_ResolvePath_Call{Call: _e.mock.On("ResolvePath", ctx, path)}
}

func (_c *MockGDriveServiceInterface_ResolvePath_Call) Run(run func(ctx context.Context, path string)) *MockGDriveServiceInterface_ResolvePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGDriveServiceInterface_ResolvePath_Call) Return(folderID string, err error) *MockGDriveServiceInterface_ResolvePath_Call {
	_c.Call.Return(folderID, err)
	return _c
}

func (_c *MockGDriveServiceInterface_ResolvePath_Call) RunAndReturn(run func(ctx context.Context, path string) (string, error)) *MockGDriveServiceInterface_ResolvePath_Call {
	_c.Call.Return(run)
	return _c
}
