// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	"github.com/jedib0t/go-pretty/v6/list"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTagsPrinter creates a new instance of MockTagsPrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagsPrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagsPrinter {
	mock := &MockTagsPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTagsPrinter is an autogenerated mock type for the TagsPrinter type
type MockTagsPrinter struct {
	mock.Mock
}

type MockTagsPrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagsPrinter) EXPECT() *MockTagsPrinter_Expecter {
	return &MockTagsPrinter_Expecter{mock: &_m.Mock}
}

// PrintTags provides a mock function for the type MockTagsPrinter
func (_mock *MockTagsPrinter) PrintTags(writer list.Writer) error {
	ret := _mock.Called(writer)

	if len(ret) == 0 {
		panic("no return value specified for PrintTags")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(list.Writer) error); ok {
		r0 = returnFunc(writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTagsPrinter_PrintTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintTags'
type MockTagsPrinter_PrintTags_Call struct {
	*mock.Call
}

// PrintTags is a helper method to define mock.On call
//   - writer list.Writer
func (_e *MockTagsPrinter_Expecter) PrintTags(writer interface{}) *MockTagsPrinter_PrintTags_Call {
	return &MockTagsPrinter_PrintTags_Call{Call: _e.mock.On("PrintTags", writer)}
}

func (_c *MockTagsPrinter_PrintTags_Call) Run(run func(writer list.Writer)) *MockTagsPrinter_PrintTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 list.Writer
		if args[0] != nil {
			arg0 = args[0].(list.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTagsPrinter_PrintTags_Call) Return(err error) *MockTagsPrinter_PrintTags_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTagsPrinter_PrintTags_Call) RunAndReturn(run func(writer list.Writer) error) *MockTagsPrinter_PrintTags_Call {
	_c.Call.Return(run)
	return _c
}
