// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	"github.com/jedib0t/go-pretty/v6/list"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodePrinter creates a new instance of MockNodePrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodePrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodePrinter {
	mock := &MockNodePrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodePrinter is an autogenerated mock type for the NodePrinter type
type MockNodePrinter struct {
	mock.Mock
}

type MockNodePrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodePrinter) EXPECT() *MockNodePrinter_Expecter {
	return &MockNodePrinter_Expecter{mock: &_m.Mock}
}

// PrintNode provides a mock function for the type MockNodePrinter
func (_mock *MockNodePrinter) PrintNode(writer list.Writer) error {
	ret := _mock.Called(writer)

	if len(ret) == 0 {
		panic("no return value specified for PrintNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(list.Writer) error); ok {
		r0 = returnFunc(writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodePrinter_PrintNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintNode'
type MockNodePrinter_PrintNode_Call struct {
	*mock.Call
}

// PrintNode is a helper method to define mock.On call
//   - writer list.Writer
func (_e *MockNodePrinter_Expecter) PrintNode(writer interface{}) *MockNodePrinter_PrintNode_Call {
	return &MockNodePrinter_PrintNode_Call{Call: _e.mock.On("PrintNode", writer)}
}

func (_c *MockNodePrinter_PrintNode_Call) Run(run func(writer list.Writer)) *MockNodePrinter_PrintNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 list.Writer
		if args[0] != nil {
			arg0 = args[0].(list.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodePrinter_PrintNode_Call) Return(err error) *MockNodePrinter_PrintNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodePrinter_PrintNode_Call) RunAndReturn(run func(writer list.Writer) error) *MockNodePrinter_PrintNode_Call {
	_c.Call.Return(run)
	return _c
}
