// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSerializableNode creates a new instance of MockSerializableNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSerializableNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSerializableNode {
	mock := &MockSerializableNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSerializableNode is an autogenerated mock type for the SerializableNode type
type MockSerializableNode struct {
	mock.Mock
}

type MockSerializableNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSerializableNode) EXPECT() *MockSerializableNode_Expecter {
	return &MockSerializableNode_Expecter{mock: &_m.Mock}
}

// MarshalJSON provides a mock function for the type MockSerializableNode
func (_mock *MockSerializableNode) MarshalJSON() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MarshalJSON")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSerializableNode_MarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalJSON'
type MockSerializableNode_MarshalJSON_Call struct {
	*mock.Call
}

// MarshalJSON is a helper method to define mock.On call
func (_e *MockSerializableNode_Expecter) MarshalJSON() *MockSerializableNode_MarshalJSON_Call {
	return &MockSerializableNode_MarshalJSON_Call{Call: _e.mock.On("MarshalJSON")}
}

func (_c *MockSerializableNode_MarshalJSON_Call) Run(run func()) *MockSerializableNode_MarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSerializableNode_MarshalJSON_Call) Return(bytes []byte, err error) *MockSerializableNode_MarshalJSON_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockSerializableNode_MarshalJSON_Call) RunAndReturn(run func() ([]byte, error)) *MockSerializableNode_MarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}

// UnmarshalJSON provides a mock function for the type MockSerializableNode
func (_mock *MockSerializableNode) UnmarshalJSON(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for UnmarshalJSON")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSerializableNode_UnmarshalJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmarshalJSON'
type MockSerializableNode_UnmarshalJSON_Call struct {
	*mock.Call
}

// UnmarshalJSON is a helper method to define mock.On call
//   - data []byte
func (_e *MockSerializableNode_Expecter) UnmarshalJSON(data interface{}) *MockSerializableNode_UnmarshalJSON_Call {
	return &MockSerializableNode_UnmarshalJSON_Call{Call: _e.mock.On("UnmarshalJSON", data)}
}

func (_c *MockSerializableNode_UnmarshalJSON_Call) Run(run func(data []byte)) *MockSerializableNode_UnmarshalJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSerializableNode_UnmarshalJSON_Call) Return(err error) *MockSerializableNode_UnmarshalJSON_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSerializableNode_UnmarshalJSON_Call) RunAndReturn(run func(data []byte) error) *MockSerializableNode_UnmarshalJSON_Call {
	_c.Call.Return(run)
	return _c
}
