// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package file

import (
	"github.com/jedib0t/go-pretty/v6/list"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdPrinter creates a new instance of MockIdPrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdPrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdPrinter {
	mock := &MockIdPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdPrinter is an autogenerated mock type for the IdPrinter type
type MockIdPrinter struct {
	mock.Mock
}

type MockIdPrinter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdPrinter) EXPECT() *MockIdPrinter_Expecter {
	return &MockIdPrinter_Expecter{mock: &_m.Mock}
}

// PrintId provides a mock function for the type MockIdPrinter
func (_mock *MockIdPrinter) PrintId(writer list.Writer) error {
	ret := _mock.Called(writer)

	if len(ret) == 0 {
		panic("no return value specified for PrintId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(list.Writer) error); ok {
		r0 = returnFunc(writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIdPrinter_PrintId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintId'
type MockIdPrinter_PrintId_Call struct {
	*mock.Call
}

// PrintId is a helper method to define mock.On call
//   - writer list.Writer
func (_e *MockIdPrinter_Expecter) PrintId(writer interface{}) *MockIdPrinter_PrintId_Call {
	return &MockIdPrinter_PrintId_Call{Call: _e.mock.On("PrintId", writer)}
}

func (_c *MockIdPrinter_PrintId_Call) Run(run func(writer list.Writer)) *MockIdPrinter_PrintId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 list.Writer
		if args[0] != nil {
			arg0 = args[0].(list.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIdPrinter_PrintId_Call) Return(err error) *MockIdPrinter_PrintId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIdPrinter_PrintId_Call) RunAndReturn(run func(writer list.Writer) error) *MockIdPrinter_PrintId_Call {
	_c.Call.Return(run)
	return _c
}
