// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTracker creates a new instance of MockTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracker {
	mock := &MockTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTracker is an autogenerated mock type for the Tracker type
type MockTracker struct {
	mock.Mock
}

type MockTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracker) EXPECT() *MockTracker_Expecter {
	return &MockTracker_Expecter{mock: &_m.Mock}
}

// Track provides a mock function for the type MockTracker
func (_mock *MockTracker) Track(path string) (*ds.TreeNode, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Track")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*ds.TreeNode, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *ds.TreeNode); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTracker_Track_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Track'
type MockTracker_Track_Call struct {
	*mock.Call
}

// Track is a helper method to define mock.On call
//   - path string
func (_e *MockTracker_Expecter) Track(path interface{}) *MockTracker_Track_Call {
	return &MockTracker_Track_Call{Call: _e.mock.On("Track", path)}
}

func (_c *MockTracker_Track_Call) Run(run func(path string)) *MockTracker_Track_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTracker_Track_Call) Return(treeNode *ds.TreeNode, err error) *MockTracker_Track_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockTracker_Track_Call) RunAndReturn(run func(path string) (*ds.TreeNode, error)) *MockTracker_Track_Call {
	_c.Call.Return(run)
	return _c
}
