// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	"github.com/heroku/self/MetaManager/internal/filesys"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScannableNode creates a new instance of MockScannableNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScannableNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScannableNode {
	mock := &MockScannableNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScannableNode is an autogenerated mock type for the ScannableNode type
type MockScannableNode struct {
	mock.Mock
}

type MockScannableNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScannableNode) EXPECT() *MockScannableNode_Expecter {
	return &MockScannableNode_Expecter{mock: &_m.Mock}
}

// ConstructTreeNode provides a mock function for the type MockScannableNode
func (_mock *MockScannableNode) ConstructTreeNode() (*ds.TreeNode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConstructTreeNode")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ds.TreeNode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ds.TreeNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScannableNode_ConstructTreeNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConstructTreeNode'
type MockScannableNode_ConstructTreeNode_Call struct {
	*mock.Call
}

// ConstructTreeNode is a helper method to define mock.On call
func (_e *MockScannableNode_Expecter) ConstructTreeNode() *MockScannableNode_ConstructTreeNode_Call {
	return &MockScannableNode_ConstructTreeNode_Call{Call: _e.mock.On("ConstructTreeNode")}
}

func (_c *MockScannableNode_ConstructTreeNode_Call) Run(run func()) *MockScannableNode_ConstructTreeNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScannableNode_ConstructTreeNode_Call) Return(treeNode *ds.TreeNode, err error) *MockScannableNode_ConstructTreeNode_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockScannableNode_ConstructTreeNode_Call) RunAndReturn(run func() (*ds.TreeNode, error)) *MockScannableNode_ConstructTreeNode_Call {
	_c.Call.Return(run)
	return _c
}

// EvalNode provides a mock function for the type MockScannableNode
func (_mock *MockScannableNode) EvalNode(scannableCxt filesys.ScannableCxt) error {
	ret := _mock.Called(scannableCxt)

	if len(ret) == 0 {
		panic("no return value specified for EvalNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(filesys.ScannableCxt) error); ok {
		r0 = returnFunc(scannableCxt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScannableNode_EvalNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalNode'
type MockScannableNode_EvalNode_Call struct {
	*mock.Call
}

// EvalNode is a helper method to define mock.On call
//   - scannableCxt filesys.ScannableCxt
func (_e *MockScannableNode_Expecter) EvalNode(scannableCxt interface{}) *MockScannableNode_EvalNode_Call {
	return &MockScannableNode_EvalNode_Call{Call: _e.mock.On("EvalNode", scannableCxt)}
}

func (_c *MockScannableNode_EvalNode_Call) Run(run func(scannableCxt filesys.ScannableCxt)) *MockScannableNode_EvalNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 filesys.ScannableCxt
		if args[0] != nil {
			arg0 = args[0].(filesys.ScannableCxt)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScannableNode_EvalNode_Call) Return(err error) *MockScannableNode_EvalNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScannableNode_EvalNode_Call) RunAndReturn(run func(scannableCxt filesys.ScannableCxt) error) *MockScannableNode_EvalNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type MockScannableNode
func (_mock *MockScannableNode) GetChildren() ([]filesys.ScannableNode, []filesys.ScannableCxt, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []filesys.ScannableNode
	var r1 []filesys.ScannableCxt
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() ([]filesys.ScannableNode, []filesys.ScannableCxt, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []filesys.ScannableNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]filesys.ScannableNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []filesys.ScannableCxt); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]filesys.ScannableCxt)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockScannableNode_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockScannableNode_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
func (_e *MockScannableNode_Expecter) GetChildren() *MockScannableNode_GetChildren_Call {
	return &MockScannableNode_GetChildren_Call{Call: _e.mock.On("GetChildren")}
}

func (_c *MockScannableNode_GetChildren_Call) Run(run func()) *MockScannableNode_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScannableNode_GetChildren_Call) Return(scannableNodes []filesys.ScannableNode, scannableCxts []filesys.ScannableCxt, err error) *MockScannableNode_GetChildren_Call {
	_c.Call.Return(scannableNodes, scannableCxts, err)
	return _c
}

func (_c *MockScannableNode_GetChildren_Call) RunAndReturn(run func() ([]filesys.ScannableNode, []filesys.ScannableCxt, error)) *MockScannableNode_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}
