// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInfoSerializer creates a new instance of MockInfoSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfoSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfoSerializer {
	mock := &MockInfoSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInfoSerializer is an autogenerated mock type for the InfoSerializer type
type MockInfoSerializer struct {
	mock.Mock
}

type MockInfoSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfoSerializer) EXPECT() *MockInfoSerializer_Expecter {
	return &MockInfoSerializer_Expecter{mock: &_m.Mock}
}

// InfoMarshal provides a mock function for the type MockInfoSerializer
func (_mock *MockInfoSerializer) InfoMarshal(treeNodeInformable ds.TreeNodeInformable) ([]byte, string, error) {
	ret := _mock.Called(treeNodeInformable)

	if len(ret) == 0 {
		panic("no return value specified for InfoMarshal")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(ds.TreeNodeInformable) ([]byte, string, error)); ok {
		return returnFunc(treeNodeInformable)
	}
	if returnFunc, ok := ret.Get(0).(func(ds.TreeNodeInformable) []byte); ok {
		r0 = returnFunc(treeNodeInformable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ds.TreeNodeInformable) string); ok {
		r1 = returnFunc(treeNodeInformable)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(ds.TreeNodeInformable) error); ok {
		r2 = returnFunc(treeNodeInformable)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInfoSerializer_InfoMarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoMarshal'
type MockInfoSerializer_InfoMarshal_Call struct {
	*mock.Call
}

// InfoMarshal is a helper method to define mock.On call
//   - treeNodeInformable ds.TreeNodeInformable
func (_e *MockInfoSerializer_Expecter) InfoMarshal(treeNodeInformable interface{}) *MockInfoSerializer_InfoMarshal_Call {
	return &MockInfoSerializer_InfoMarshal_Call{Call: _e.mock.On("InfoMarshal", treeNodeInformable)}
}

func (_c *MockInfoSerializer_InfoMarshal_Call) Run(run func(treeNodeInformable ds.TreeNodeInformable)) *MockInfoSerializer_InfoMarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ds.TreeNodeInformable
		if args[0] != nil {
			arg0 = args[0].(ds.TreeNodeInformable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInfoSerializer_InfoMarshal_Call) Return(bytes []byte, s string, err error) *MockInfoSerializer_InfoMarshal_Call {
	_c.Call.Return(bytes, s, err)
	return _c
}

func (_c *MockInfoSerializer_InfoMarshal_Call) RunAndReturn(run func(treeNodeInformable ds.TreeNodeInformable) ([]byte, string, error)) *MockInfoSerializer_InfoMarshal_Call {
	_c.Call.Return(run)
	return _c
}

// InfoUnmarshal provides a mock function for the type MockInfoSerializer
func (_mock *MockInfoSerializer) InfoUnmarshal(bytes []byte, s string) (ds.TreeNodeInformable, error) {
	ret := _mock.Called(bytes, s)

	if len(ret) == 0 {
		panic("no return value specified for InfoUnmarshal")
	}

	var r0 ds.TreeNodeInformable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, string) (ds.TreeNodeInformable, error)); ok {
		return returnFunc(bytes, s)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, string) ds.TreeNodeInformable); ok {
		r0 = returnFunc(bytes, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ds.TreeNodeInformable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = returnFunc(bytes, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInfoSerializer_InfoUnmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoUnmarshal'
type MockInfoSerializer_InfoUnmarshal_Call struct {
	*mock.Call
}

// InfoUnmarshal is a helper method to define mock.On call
//   - bytes []byte
//   - s string
func (_e *MockInfoSerializer_Expecter) InfoUnmarshal(bytes interface{}, s interface{}) *MockInfoSerializer_InfoUnmarshal_Call {
	return &MockInfoSerializer_InfoUnmarshal_Call{Call: _e.mock.On("InfoUnmarshal", bytes, s)}
}

func (_c *MockInfoSerializer_InfoUnmarshal_Call) Run(run func(bytes []byte, s string)) *MockInfoSerializer_InfoUnmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInfoSerializer_InfoUnmarshal_Call) Return(treeNodeInformable ds.TreeNodeInformable, err error) *MockInfoSerializer_InfoUnmarshal_Call {
	_c.Call.Return(treeNodeInformable, err)
	return _c
}

func (_c *MockInfoSerializer_InfoUnmarshal_Call) RunAndReturn(run func(bytes []byte, s string) (ds.TreeNodeInformable, error)) *MockInfoSerializer_InfoUnmarshal_Call {
	_c.Call.Return(run)
	return _c
}
