// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeIterable creates a new instance of MockNodeIterable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeIterable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeIterable {
	mock := &MockNodeIterable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeIterable is an autogenerated mock type for the NodeIterable type
type MockNodeIterable struct {
	mock.Mock
}

type MockNodeIterable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeIterable) EXPECT() *MockNodeIterable_Expecter {
	return &MockNodeIterable_Expecter{mock: &_m.Mock}
}

// GetChildren provides a mock function for the type MockNodeIterable
func (_mock *MockNodeIterable) GetChildren() []ds.NodeIterable {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []ds.NodeIterable
	if returnFunc, ok := ret.Get(0).(func() []ds.NodeIterable); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ds.NodeIterable)
		}
	}
	return r0
}

// MockNodeIterable_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockNodeIterable_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
func (_e *MockNodeIterable_Expecter) GetChildren() *MockNodeIterable_GetChildren_Call {
	return &MockNodeIterable_GetChildren_Call{Call: _e.mock.On("GetChildren")}
}

func (_c *MockNodeIterable_GetChildren_Call) Run(run func()) *MockNodeIterable_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeIterable_GetChildren_Call) Return(nodeIterables []ds.NodeIterable) *MockNodeIterable_GetChildren_Call {
	_c.Call.Return(nodeIterables)
	return _c
}

func (_c *MockNodeIterable_GetChildren_Call) RunAndReturn(run func() []ds.NodeIterable) *MockNodeIterable_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}
