// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ds

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeNodeInformable creates a new instance of MockTreeNodeInformable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeNodeInformable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeNodeInformable {
	mock := &MockTreeNodeInformable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeNodeInformable is an autogenerated mock type for the TreeNodeInformable type
type MockTreeNodeInformable struct {
	mock.Mock
}

type MockTreeNodeInformable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeNodeInformable) EXPECT() *MockTreeNodeInformable_Expecter {
	return &MockTreeNodeInformable_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockTreeNodeInformable
func (_mock *MockTreeNodeInformable) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTreeNodeInformable_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTreeNodeInformable_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTreeNodeInformable_Expecter) Name() *MockTreeNodeInformable_Name_Call {
	return &MockTreeNodeInformable_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTreeNodeInformable_Name_Call) Run(run func()) *MockTreeNodeInformable_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTreeNodeInformable_Name_Call) Return(s string) *MockTreeNodeInformable_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTreeNodeInformable_Name_Call) RunAndReturn(run func() string) *MockTreeNodeInformable_Name_Call {
	_c.Call.Return(run)
	return _c
}
