// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ds

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInfoUnmarshaler creates a new instance of MockInfoUnmarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInfoUnmarshaler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInfoUnmarshaler {
	mock := &MockInfoUnmarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInfoUnmarshaler is an autogenerated mock type for the InfoUnmarshaler type
type MockInfoUnmarshaler struct {
	mock.Mock
}

type MockInfoUnmarshaler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInfoUnmarshaler) EXPECT() *MockInfoUnmarshaler_Expecter {
	return &MockInfoUnmarshaler_Expecter{mock: &_m.Mock}
}

// InfoUnmarshal provides a mock function for the type MockInfoUnmarshaler
func (_mock *MockInfoUnmarshaler) InfoUnmarshal(stringToIfaceVal map[string]interface{}) (ds.TreeNodeInformable, error) {
	ret := _mock.Called(stringToIfaceVal)

	if len(ret) == 0 {
		panic("no return value specified for InfoUnmarshal")
	}

	var r0 ds.TreeNodeInformable
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) (ds.TreeNodeInformable, error)); ok {
		return returnFunc(stringToIfaceVal)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) ds.TreeNodeInformable); ok {
		r0 = returnFunc(stringToIfaceVal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ds.TreeNodeInformable)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = returnFunc(stringToIfaceVal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInfoUnmarshaler_InfoUnmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoUnmarshal'
type MockInfoUnmarshaler_InfoUnmarshal_Call struct {
	*mock.Call
}

// InfoUnmarshal is a helper method to define mock.On call
//   - stringToIfaceVal map[string]interface{}
func (_e *MockInfoUnmarshaler_Expecter) InfoUnmarshal(stringToIfaceVal interface{}) *MockInfoUnmarshaler_InfoUnmarshal_Call {
	return &MockInfoUnmarshaler_InfoUnmarshal_Call{Call: _e.mock.On("InfoUnmarshal", stringToIfaceVal)}
}

func (_c *MockInfoUnmarshaler_InfoUnmarshal_Call) Run(run func(stringToIfaceVal map[string]interface{})) *MockInfoUnmarshaler_InfoUnmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockInfoUnmarshaler_InfoUnmarshal_Call) Return(treeNodeInformable ds.TreeNodeInformable, err error) *MockInfoUnmarshaler_InfoUnmarshal_Call {
	_c.Call.Return(treeNodeInformable, err)
	return _c
}

func (_c *MockInfoUnmarshaler_InfoUnmarshal_Call) RunAndReturn(run func(stringToIfaceVal map[string]interface{}) (ds.TreeNodeInformable, error)) *MockInfoUnmarshaler_InfoUnmarshal_Call {
	_c.Call.Return(run)
	return _c
}
