// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ds

import (
	"github.com/heroku/self/MetaManager/internal/ds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTreeIterable creates a new instance of MockTreeIterable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTreeIterable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTreeIterable {
	mock := &MockTreeIterable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTreeIterable is an autogenerated mock type for the TreeIterable type
type MockTreeIterable struct {
	mock.Mock
}

type MockTreeIterable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTreeIterable) EXPECT() *MockTreeIterable_Expecter {
	return &MockTreeIterable_Expecter{mock: &_m.Mock}
}

// HasNext provides a mock function for the type MockTreeIterable
func (_mock *MockTreeIterable) HasNext() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTreeIterable_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type MockTreeIterable_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *MockTreeIterable_Expecter) HasNext() *MockTreeIterable_HasNext_Call {
	return &MockTreeIterable_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *MockTreeIterable_HasNext_Call) Run(run func()) *MockTreeIterable_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTreeIterable_HasNext_Call) Return(b bool) *MockTreeIterable_HasNext_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTreeIterable_HasNext_Call) RunAndReturn(run func() bool) *MockTreeIterable_HasNext_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockTreeIterable
func (_mock *MockTreeIterable) Next() (*ds.TreeNode, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *ds.TreeNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*ds.TreeNode, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *ds.TreeNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.TreeNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTreeIterable_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockTreeIterable_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockTreeIterable_Expecter) Next() *MockTreeIterable_Next_Call {
	return &MockTreeIterable_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockTreeIterable_Next_Call) Run(run func()) *MockTreeIterable_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTreeIterable_Next_Call) Return(treeNode *ds.TreeNode, err error) *MockTreeIterable_Next_Call {
	_c.Call.Return(treeNode, err)
	return _c
}

func (_c *MockTreeIterable_Next_Call) RunAndReturn(run func() (*ds.TreeNode, error)) *MockTreeIterable_Next_Call {
	_c.Call.Return(run)
	return _c
}
