// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/file"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPrintingContext creates a new instance of MockPrintingContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrintingContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrintingContext {
	mock := &MockPrintingContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPrintingContext is an autogenerated mock type for the PrintingContext type
type MockPrintingContext struct {
	mock.Mock
}

type MockPrintingContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrintingContext) EXPECT() *MockPrintingContext_Expecter {
	return &MockPrintingContext_Expecter{mock: &_m.Mock}
}

// GetPrinter provides a mock function for the type MockPrintingContext
func (_mock *MockPrintingContext) GetPrinter(info any) (file.PrinterFunc, error) {
	ret := _mock.Called(info)

	if len(ret) == 0 {
		panic("no return value specified for GetPrinter")
	}

	var r0 file.PrinterFunc
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(any) (file.PrinterFunc, error)); ok {
		return returnFunc(info)
	}
	if returnFunc, ok := ret.Get(0).(func(any) file.PrinterFunc); ok {
		r0 = returnFunc(info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(file.PrinterFunc)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(any) error); ok {
		r1 = returnFunc(info)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPrintingContext_GetPrinter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrinter'
type MockPrintingContext_GetPrinter_Call struct {
	*mock.Call
}

// GetPrinter is a helper method to define mock.On call
//   - info any
func (_e *MockPrintingContext_Expecter) GetPrinter(info interface{}) *MockPrintingContext_GetPrinter_Call {
	return &MockPrintingContext_GetPrinter_Call{Call: _e.mock.On("GetPrinter", info)}
}

func (_c *MockPrintingContext_GetPrinter_Call) Run(run func(info any)) *MockPrintingContext_GetPrinter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPrintingContext_GetPrinter_Call) Return(printerFunc file.PrinterFunc, err error) *MockPrintingContext_GetPrinter_Call {
	_c.Call.Return(printerFunc, err)
	return _c
}

func (_c *MockPrintingContext_GetPrinter_Call) RunAndReturn(run func(info any) (file.PrinterFunc, error)) *MockPrintingContext_GetPrinter_Call {
	_c.Call.Return(run)
	return _c
}
