// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/heroku/self/MetaManager/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRWFactory creates a new instance of MockRWFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRWFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRWFactory {
	mock := &MockRWFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRWFactory is an autogenerated mock type for the RWFactory type
type MockRWFactory struct {
	mock.Mock
}

type MockRWFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRWFactory) EXPECT() *MockRWFactory_Expecter {
	return &MockRWFactory_Expecter{mock: &_m.Mock}
}

// GetTreeRW provides a mock function for the type MockRWFactory
func (_mock *MockRWFactory) GetTreeRW() (storage.TreeRW, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTreeRW")
	}

	var r0 storage.TreeRW
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (storage.TreeRW, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() storage.TreeRW); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(storage.TreeRW)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRWFactory_GetTreeRW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTreeRW'
type MockRWFactory_GetTreeRW_Call struct {
	*mock.Call
}

// GetTreeRW is a helper method to define mock.On call
func (_e *MockRWFactory_Expecter) GetTreeRW() *MockRWFactory_GetTreeRW_Call {
	return &MockRWFactory_GetTreeRW_Call{Call: _e.mock.On("GetTreeRW")}
}

func (_c *MockRWFactory_GetTreeRW_Call) Run(run func()) *MockRWFactory_GetTreeRW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRWFactory_GetTreeRW_Call) Return(treeRW storage.TreeRW, err error) *MockRWFactory_GetTreeRW_Call {
	_c.Call.Return(treeRW, err)
	return _c
}

func (_c *MockRWFactory_GetTreeRW_Call) RunAndReturn(run func() (storage.TreeRW, error)) *MockRWFactory_GetTreeRW_Call {
	_c.Call.Return(run)
	return _c
}
