// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filesys

import (
	filesys "github.com/heroku/self/MetaManager/internal/repository/context"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextRepository creates a new instance of MockContextRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextRepository {
	mock := &MockContextRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextRepository is an autogenerated mock type for the ContextRepository type
type MockContextRepository struct {
	mock.Mock
}

type MockContextRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextRepository) EXPECT() *MockContextRepository_Expecter {
	return &MockContextRepository_Expecter{mock: &_m.Mock}
}

// AddContext provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) AddContext(name string, contextType string) error {
	ret := _mock.Called(name, contextType)

	if len(ret) == 0 {
		panic("no return value specified for AddContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, contextType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_AddContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddContext'
type MockContextRepository_AddContext_Call struct {
	*mock.Call
}

// AddContext is a helper method to define mock.On call
//   - name string
//   - contextType string
func (_e *MockContextRepository_Expecter) AddContext(name interface{}, contextType interface{}) *MockContextRepository_AddContext_Call {
	return &MockContextRepository_AddContext_Call{Call: _e.mock.On("AddContext", name, contextType)}
}

func (_c *MockContextRepository_AddContext_Call) Run(run func(name string, contextType string)) *MockContextRepository_AddContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextRepository_AddContext_Call) Return(err error) *MockContextRepository_AddContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_AddContext_Call) RunAndReturn(run func(name string, contextType string) error) *MockContextRepository_AddContext_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) Create(name string, contextType string) error {
	ret := _mock.Called(name, contextType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(name, contextType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockContextRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - name string
//   - contextType string
func (_e *MockContextRepository_Expecter) Create(name interface{}, contextType interface{}) *MockContextRepository_Create_Call {
	return &MockContextRepository_Create_Call{Call: _e.mock.On("Create", name, contextType)}
}

func (_c *MockContextRepository_Create_Call) Run(run func(name string, contextType string)) *MockContextRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContextRepository_Create_Call) Return(err error) *MockContextRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_Create_Call) RunAndReturn(run func(name string, contextType string) error) *MockContextRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) Delete(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContextRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - name string
func (_e *MockContextRepository_Expecter) Delete(name interface{}) *MockContextRepository_Delete_Call {
	return &MockContextRepository_Delete_Call{Call: _e.mock.On("Delete", name)}
}

func (_c *MockContextRepository_Delete_Call) Run(run func(name string)) *MockContextRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextRepository_Delete_Call) Return(err error) *MockContextRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_Delete_Call) RunAndReturn(run func(name string) error) *MockContextRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAll provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) DeleteAll() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_DeleteAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAll'
type MockContextRepository_DeleteAll_Call struct {
	*mock.Call
}

// DeleteAll is a helper method to define mock.On call
func (_e *MockContextRepository_Expecter) DeleteAll() *MockContextRepository_DeleteAll_Call {
	return &MockContextRepository_DeleteAll_Call{Call: _e.mock.On("DeleteAll")}
}

func (_c *MockContextRepository_DeleteAll_Call) Run(run func()) *MockContextRepository_DeleteAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContextRepository_DeleteAll_Call) Return(err error) *MockContextRepository_DeleteAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_DeleteAll_Call) RunAndReturn(run func() error) *MockContextRepository_DeleteAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetContext provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) GetContext() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetContext")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextRepository_GetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContext'
type MockContextRepository_GetContext_Call struct {
	*mock.Call
}

// GetContext is a helper method to define mock.On call
func (_e *MockContextRepository_Expecter) GetContext() *MockContextRepository_GetContext_Call {
	return &MockContextRepository_GetContext_Call{Call: _e.mock.On("GetContext")}
}

func (_c *MockContextRepository_GetContext_Call) Run(run func()) *MockContextRepository_GetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContextRepository_GetContext_Call) Return(s string, err error) *MockContextRepository_GetContext_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockContextRepository_GetContext_Call) RunAndReturn(run func() (string, error)) *MockContextRepository_GetContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetContextType provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) GetContextType(name string) (string, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetContextType")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextRepository_GetContextType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContextType'
type MockContextRepository_GetContextType_Call struct {
	*mock.Call
}

// GetContextType is a helper method to define mock.On call
//   - name string
func (_e *MockContextRepository_Expecter) GetContextType(name interface{}) *MockContextRepository_GetContextType_Call {
	return &MockContextRepository_GetContextType_Call{Call: _e.mock.On("GetContextType", name)}
}

func (_c *MockContextRepository_GetContextType_Call) Run(run func(name string)) *MockContextRepository_GetContextType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextRepository_GetContextType_Call) Return(s string, err error) *MockContextRepository_GetContextType_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockContextRepository_GetContextType_Call) RunAndReturn(run func(name string) (string, error)) *MockContextRepository_GetContextType_Call {
	_c.Call.Return(run)
	return _c
}

// GetGDriveCwd provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) GetGDriveCwd() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGDriveCwd")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextRepository_GetGDriveCwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGDriveCwd'
type MockContextRepository_GetGDriveCwd_Call struct {
	*mock.Call
}

// GetGDriveCwd is a helper method to define mock.On call
func (_e *MockContextRepository_Expecter) GetGDriveCwd() *MockContextRepository_GetGDriveCwd_Call {
	return &MockContextRepository_GetGDriveCwd_Call{Call: _e.mock.On("GetGDriveCwd")}
}

func (_c *MockContextRepository_GetGDriveCwd_Call) Run(run func()) *MockContextRepository_GetGDriveCwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContextRepository_GetGDriveCwd_Call) Return(s string, err error) *MockContextRepository_GetGDriveCwd_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockContextRepository_GetGDriveCwd_Call) RunAndReturn(run func() (string, error)) *MockContextRepository_GetGDriveCwd_Call {
	_c.Call.Return(run)
	return _c
}

// LoadContexts provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) LoadContexts() ([]filesys.ContextEntry, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadContexts")
	}

	var r0 []filesys.ContextEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]filesys.ContextEntry, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []filesys.ContextEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]filesys.ContextEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextRepository_LoadContexts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadContexts'
type MockContextRepository_LoadContexts_Call struct {
	*mock.Call
}

// LoadContexts is a helper method to define mock.On call
func (_e *MockContextRepository_Expecter) LoadContexts() *MockContextRepository_LoadContexts_Call {
	return &MockContextRepository_LoadContexts_Call{Call: _e.mock.On("LoadContexts")}
}

func (_c *MockContextRepository_LoadContexts_Call) Run(run func()) *MockContextRepository_LoadContexts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContextRepository_LoadContexts_Call) Return(contextEntrys []filesys.ContextEntry, err error) *MockContextRepository_LoadContexts_Call {
	_c.Call.Return(contextEntrys, err)
	return _c
}

func (_c *MockContextRepository_LoadContexts_Call) RunAndReturn(run func() ([]filesys.ContextEntry, error)) *MockContextRepository_LoadContexts_Call {
	_c.Call.Return(run)
	return _c
}

// SetCurrent provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) SetCurrent(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for SetCurrent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_SetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCurrent'
type MockContextRepository_SetCurrent_Call struct {
	*mock.Call
}

// SetCurrent is a helper method to define mock.On call
//   - name string
func (_e *MockContextRepository_Expecter) SetCurrent(name interface{}) *MockContextRepository_SetCurrent_Call {
	return &MockContextRepository_SetCurrent_Call{Call: _e.mock.On("SetCurrent", name)}
}

func (_c *MockContextRepository_SetCurrent_Call) Run(run func(name string)) *MockContextRepository_SetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextRepository_SetCurrent_Call) Return(err error) *MockContextRepository_SetCurrent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_SetCurrent_Call) RunAndReturn(run func(name string) error) *MockContextRepository_SetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// SetGDriveCwd provides a mock function for the type MockContextRepository
func (_mock *MockContextRepository) SetGDriveCwd(path string) error {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for SetGDriveCwd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockContextRepository_SetGDriveCwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGDriveCwd'
type MockContextRepository_SetGDriveCwd_Call struct {
	*mock.Call
}

// SetGDriveCwd is a helper method to define mock.On call
//   - path string
func (_e *MockContextRepository_Expecter) SetGDriveCwd(path interface{}) *MockContextRepository_SetGDriveCwd_Call {
	return &MockContextRepository_SetGDriveCwd_Call{Call: _e.mock.On("SetGDriveCwd", path)}
}

func (_c *MockContextRepository_SetGDriveCwd_Call) Run(run func(path string)) *MockContextRepository_SetGDriveCwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextRepository_SetGDriveCwd_Call) Return(err error) *MockContextRepository_SetGDriveCwd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockContextRepository_SetGDriveCwd_Call) RunAndReturn(run func(path string) error) *MockContextRepository_SetGDriveCwd_Call {
	_c.Call.Return(run)
	return _c
}
